language: go

jobs:
  include:
    - stage: Test
      go: 1.11.x
      dist: xenial
      script:
        -  psql -c 'create database goby_test;' -U postgres
        - ./travis.sh
    # trusty builds with 1.11 are [currently broken](https://github.com/golang/go/issues/31293)
    - go: 1.12.x
      dist: trusty
      script:
        -  psql -c 'create database goby_test;' -U postgres
        - ./travis.sh
    - go: 1.12.x
      dist: xenial
      script:
        -  psql -c 'create database goby_test;' -U postgres
        - ./travis.sh
    
    - stage: Fuzz regression
      go: 1.12.x
      dist: bionic
      script: ./fuzzit.sh local-regression

    - stage: Fuzz
      if: branch = master AND type IN (push)
      go: 1.12.x
      dist: bionic
      script: ./fuzzit.sh fuzzing

services:
  - postgresql
  - docker

go_import_path: github.com/goby-lang/goby

before_install:
  - sudo apt-get install apache2-utils

env:
  global:
    - "GOBY_ROOT=$HOME/gopath/src/github.com/goby-lang/goby"
    # FUZZIT_API_KEY
    - secure: "FEm1wF/Ttd5RIvDPg5I/aSAhBWuvkvjmkInFxlVKP4BfLsR1B1ogXV4zKFQiZugyppBta+qP4qP+tSbThSvP9JOCr+/ivnTyYLg/DH1RfQnC7rJmAaZwHGHB+NwblRzU621uIZ4RVvaE391YVJf5519gc+M+bxZ6DO0ScdpbIAVV/7JR9c7Tuvoyi57/MEwAS39k7h83ms8JgRYwuvzpVH9nb6AfYs+CzXuRlsG5mHqFnmzLyG0ewnqh18OoWbyKQwBmM+EoIGmckM8NQZaXWBhEuDP7qdl+QatNfZtK3YwBx2plahBXXMee3NpOAEHOkWxNw1uMb1B8ILDrzrx8oX1A4fF/ZeJl7JLZS/fQUMhDnLG5soA0xaEoAvwhQIHFi3e207rsq9UJsnQlRGhRWzMvx85UR5z+yiur8nVUkogu1DGpH/BPdWbTs+d8behSr7t6Sepo7enjJOPJLz6U67JlP31HvnaLICMEXxJy54BAbdu/47vqFp15lcIMHyDzPltHHWi6uGuRFQPYz8pM5ZAKQ945dO/ZELyEHbjUiLTMFeVoANzahuY56BX6hvsygcOlBWB6ukoJANvxgvM/QYkbh9dMBajYsZqHCWOKRVbBakkqPAUqkBNPOADTp5ZgUwmRySIGzX2X+Efl7cFYZVu+IJl968F8hqYajvS/VCs="

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    rooms:
      - goby-lang:Ler5Uge2Vlx3O8Yt2OFcKg5W#general
    on_success: always
    on_failure: always
    on_start: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/149378fb1b44bbaf21f0
    on_success: change
    on_failure: always
    on_start: never
  email:
    recipients:
      - stan001212@gmail.com
    on_failure: change
    on_success: never
